# Generated by Django 3.1.2 on 2020-10-16 12:20

import apps.usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=apps.usuario.models.custom_upload)),
                ('numero_usuario', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
